//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Bicis_Scooters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_VENTAS_BICICLETA_SCOOTEREntities1 : DbContext
    {
        public BD_VENTAS_BICICLETA_SCOOTEREntities1()
            : base("name=BD_VENTAS_BICICLETA_SCOOTEREntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_IMAGENES> TB_IMAGENES { get; set; }
    }
}
