//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Bicis_Scooters.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_VENTAS_BICICLETA_SCOOTEREntities : DbContext
    {
        public BD_VENTAS_BICICLETA_SCOOTEREntities()
            : base("name=BD_VENTAS_BICICLETA_SCOOTEREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_IMAGENES> TB_IMAGENES { get; set; }
        public virtual DbSet<TB_DETALLE_PEDIDOS> TB_DETALLE_PEDIDOS { get; set; }
        public virtual DbSet<TB_PEDIDO> TB_PEDIDO { get; set; }
    
        public virtual ObjectResult<usp_Pedido_Listar_Result> usp_Pedido_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Pedido_Listar_Result>("usp_Pedido_Listar");
        }
    }
}
