//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Bicis_Scooters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DETALLE_PEDIDOS
    {
        public int cod_detalle_pedido { get; set; }
        public int nro_pedido { get; set; }
        public int cod_bicicleta { get; set; }
        public int cantidad { get; set; }
        public decimal total { get; set; }
    
        public virtual TB_PEDIDO TB_PEDIDO { get; set; }
    }
}
