//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Venta_Bicis_Scooters.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_IMAGENES
    {
        public int cod_imagen { get; set; }
        public string descrp_imagen { get; set; }
        public byte[] url_imagen { get; set; }
    }
}
